source "http://rubygems.org"
source "http://gems.github.com"

gem "rails",            "3.0.4"
gem "sqlite3-ruby",     "1.3.3", :require => "sqlite3"
gem "devise",           "1.1.7"
gem "formtastic",       "1.2.3"
gem "seed-fu",          "1.2.3"
gem "state_machine",    "0.9.4"
gem "peterpunk-mhash",  "0.0.8"
gem "haml",             "3.0.24"
gem "compass",          ">= 0.10.6"
