source "http://rubygems.org"
source "http://gems.github.com"

gem "rails",            "2.3.10"
gem "sqlite3-ruby",     "1.3.2", :require => "sqlite3"
gem "devise",           "1.0.9"
gem "formtastic",       "1.2.2"
gem "seed-fu",          "1.2.3"
gem "state_machine",    "0.9.4"
gem "peterpunk-mhash",  "0.0.8"
gem "haml",             "3.0.24"
gem "compass", ">= 0.10.6"
